import Header from "@/components/header/Header";
import { Footer } from "@/components/footer/Footer";
import FloatingButton from "@/components/ui/floatingButton/FloatingButton";
import "./globals.scss";


export const metadata = {
  title: "Life Institut AG ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='main-layout-section'>
          <div className='header-section'>
            <Header />
          </div>
          <div className='body-section'>
            <main>
              {children}
            </main>

          </div>
          <div className='footer-section'>
            <Footer />
          </div>
        </div>
        <FloatingButton />
      </body>
    </html>
  );
}
